export const REACT_APP_API="https://threefury-back.onrender.com/api"
export const REACT_APP_PUBLIC_KEY="CY5A1KuW954jeFg5k"
export const  REACT_APP_SERVICE_ID="service_exyu2dc"
export const  REACT_APP_TEMPLATE_ID="template_ds6ptms"
export const  REACT_APP_CUSTOMER_TEMPLATE_ID="template_ysntlv1"